# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 360)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.city_label = QtWidgets.QLabel(Form)
        self.city_label.setObjectName("city_label")
        self.verticalLayout.addWidget(self.city_label)
        self.city_input = QtWidgets.QLineEdit(Form)
        self.city_input.setEnabled(True)
        self.city_input.setObjectName("city_input")
        self.verticalLayout.addWidget(self.city_input)
        self.get_weather_button = QtWidgets.QPushButton(Form)
        self.get_weather_button.setObjectName("get_weather_button")
        self.verticalLayout.addWidget(self.get_weather_button)
        self.weather_info_label = QtWidgets.QLabel(Form)
        self.weather_info_label.setText("")
        self.weather_info_label.setObjectName("weather_info_label")
        self.verticalLayout.addWidget(self.weather_info_label)
        self.history_button = QtWidgets.QPushButton(Form)
        self.history_button.setObjectName("history_button")
        self.verticalLayout.addWidget(self.history_button)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gif_label = QtWidgets.QLabel(Form)
        self.gif_label.setEnabled(True)
        self.gif_label.setMinimumSize(QtCore.QSize(0, 0))
        self.gif_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gif_label.setStyleSheet("QLabel { background-image: url(tudasuda.gif); background-repeat: no-repeat; background-position: center; }")
        self.gif_label.setText("")
        self.gif_label.setScaledContents(False)
        self.gif_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gif_label.setObjectName("gif_label")
        self.verticalLayout_2.addWidget(self.gif_label)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.city_label.setText(_translate("Form", "Введите город:"))
        self.get_weather_button.setText(_translate("Form", "Получить погоду"))
        self.history_button.setText(_translate("Form", "История запросов"))